### ISSUE TITLE
Problem with raspberry pi 3 docker image

### ISSUE THREAD

**Issue by hufon** [home-assistant/hassio-homeassistant#50]
Since hass will not support python 3.5 anymore, i try to switch on docker with docker compose

Here's my docker-compose file
```
version: '3'
  services:
    homeassistant:
      container_name: home-assistant
      image: homeassistant/raspberrypi3-homeassistant:0.94.4
      volumes:
        - /home/homeassistant/.homeassistant/:/config
        - /etc/localtime:/etc/localtime:ro
      restart: always
      network_mode: host
```

and when i start docker-compose up...

pi@piyubserver ~/prg/docker-hass $ docker-compose up
home-assistant is up-to-date
Attaching to home-assistant
home-assistant   | starting version 3.2.7
home-assistant   | Error loading shared library libpython3.7m.so.1.0: No error information (needed by /usr/local/bin/python3)
home-assistant   | Error relocating /usr/local/bin/python3: _Py_UnixMain: symbol not found
